<?php

// Implements hook_menu().
function social_menu() {
  $items = array();
  $items['friends'] = array(
    'title' => 'Friend list',
    'description' => 'A list of friends',
    'page callback' => 'social_friend_list',
    'access callback' => TRUE,
    'weight' => 1,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['requests'] = array(
    'title' => 'Friend requests',
    'page callback' => 'friend_requests',
    'access callback' => TRUE,
    'weight' => 0,
  );
  $items['wall'] = array(
    'title' => 'Wall posts',
    'page callback' => 'social_wall_posts',
    'access callback' => 'social_logged_in',
    'type' => MENU_CALLBACK,
  );

  $items['post/%/edit'] = array(
    'title' => 'Edit post',
    'page callback' => 'social_edit_post',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  
  $items['frontpage'] = array(
    'title' => 'Front Page',
    'page callback' => 'social_front_page',
    'access callback' => TRUE,
    'weight' => 0,
    'type'=> MENU_CALLBACK,
  );


  return $items;
}

function social_get_users($limit = 9){
  $output=array();
  $results = db_select('friends', 'f')
      ->fields('f', array('fid'))
      ->condition('f.uid', $user->uid, '=')
      ->execute();
  
}

function social_front_page(){
  $output = '';
  
  if(!user_is_logged_in()){
    $output['#prefix'] = '<div class="row-fluid">';
    $output['#suffix'] = '</div>';
    
    $output['left'] = array(
      '#prefix' => '<div class="span6">',
      '#suffix' => '</div>',
      '#markup' => social_get_users(),
      '#weight' => 0,
    );
    
    $output['right'] = array(
      '#prefix' => '<div class="span6">',
      '#suffix' => '</div>',
      '#weight' => 1,
    ); 
        
    $form = drupal_get_form('user_register_form');
    $output['right']['#markup'] = drupal_render($form);
  }
  else{
    drupal_goto('wall');
  }
  
  return $output;
}

function social_friend_list() {
  $output = '';
  global $user, $base_url;
  $theme_path = $base_url . '/' . drupal_get_path('theme', 'social');
  
  $results = db_select('friends', 'f')
      ->fields('f', array('fid'))
      ->condition('f.uid', $user->uid, '=')
      ->execute();

  $items = array();
  $i = 0;

  foreach ($results as $record) {
    $profile = profile2_load_by_user($record->fid);
    $profile = reset($profile);
    if (empty($profile) || empty($profile->field_nume))  {
      continue;
    }

    if ($i % 3 == 0) {
      $output .= "<div class='row-fluid'>";
      $output .= '<div class="span12">';
      $output .= '<ul class="thumbnails">';
    }

    $output .= '<li class="span4">';
    $output .= '<div class="thumbnail">';

    if (isset($profile->field_poza) && !empty($profile->field_poza)) {
      $path = $profile->field_poza["und"][0]["uri"];
      $output .= theme('image_style', array('style_name' => 'medium', 'path' => $path)); 
    }
    else{
      $path = $theme_path . '/img/blank-profile-hi.png';
      $output .= theme('image', array('width' => '220', 'path' => $path)); 
    }
    $output .= '<div class="caption">
							<h3>';
    @$output .= $profile->field_nume['und'][0]['value'] . " " . $profile->field_prenume['und'][0]['value'];
    $output .= "</h3>
							<p>
								
							</p>
						</div>
					</div>
				</li>";
    $i++;
    
    if ($i%3 == 0 && $i != 0) {
      $output .="        </ul>
          </div>
        </div>";
    }
  }

  return $output;
  return '';
}

function friend_requests() {
  $output = array();
  global $user;
 
  $query = db_select('friend_requests', 'fr');
  $query->addField('fr', 'from', 't');
  $results = $query->condition('fr.to', $user->uid, '=')
      ->execute();

  $items = array();
 
  foreach ($results as $record) {
    
    $profile = profile2_load_by_user($record->t);
    if(empty($profile)) {
      continue;
    }
    
    $profile = reset($profile);
    $p = profile2_view($profile, 'teaser');
    $items[] = drupal_render($p);
    
   
  }


  $output['friends'] = array(
    '#theme' => 'item_list',
    '#items' => $items,
    '#type' => 'ul',
  );

  return $output;
  return '';
}

function social_wall_posts() {
  $limit = 2;
  $output = array();
  global $user;
  $results = db_select('node', 'n');
  $results->join('friends', 'f', 'f.fid = n.uid OR n.uid = ' . $user->uid);
  $results = $results->fields('n', array('nid', 'title'))
      ->condition('f.uid', $user->uid)
      ->condition('n.type', 'post')
      ->orderBy('n.created', 'DESC')
      ->extend('PagerDefault')
      ->limit($limit)
      ->execute();

  $items = array();
  foreach ($results as $record) {

    $node = node_load($record->nid);
    $post = node_view($node, 'teaser');
    $post = drupal_render($post);

    $items[] = $post;
  }

//return theme('item_list', array('items' => $items));
  $output['posts'] = array(
    '#theme' => 'item_list',
    '#items' => $items,
  );
  
  $output['pager'] = array('#theme' => 'pager');

  return $output;
}

function social_logged_in() {
  global $user;
  if ($user->uid)
    return TRUE;
  return FALSE;
}

function social_edit_post($pid = 1) {
  return $pid;
}


